export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';
export const SET_IS_FORM_SUBMITTED = 'SET_IS_FORM_SUBMITTED';
export const SET_IS_FORM_VALID = 'SET_IS_FORM_VALID';
export const REMOVE_INPUT_ERROR = 'REMOVE_INPUT_ERROR';
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM';